server:
  port: 8761

  eureka:
    instance:
      hostname: localhost 
    client:
      service-url:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eurek
      register-with-eureka: false
      fetch-registry: false
spring:
  application:
    name: eureka-server
